import("//args.gni")

config("build_config") {
  if (enable_memory_test) {
    defines = [ "MEMORY_TEST" ]
  }
}

executable("zero") {
  sources = [
    "//main.c",
    "//map.c",
    "//map.h",
    "//mm.c",
    "//mm.h",
    "//vec.c",
    "//vec.h",
    "//zero.h",
  ]

  configs += [ ":build_config" ]
}
